// This file is generated by Slice Machine. Update with care!

export { default as Cover } from './Cover'
export { default as Features } from './Features'
export { default as ImageAndText } from './ImageAndText'
export { default as Logos } from './Logos'
export { default as Numbers } from './Numbers'
export { default as Teasers } from './Teasers'
export { default as Testimonials } from './Testimonials'
